// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookManagementUsing3tierMVCwithJQuery.Resource
{
    public partial class AdminLogin
    {
        public string AdminId { get; set; }
        public byte[] AdminPassword { get; set; }
        public byte[] AdminPasswordKey { get; set; }
        public DateTime CreateTimeStamp { get; set; }
        public DateTime UpdateTimeStamp { get; set; }
        public bool IsDeleted { get; set; }
    }
}