// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookManagementUsing3tierMVCwithJQuery.Resource
{
    public partial class BookDetail
    {
        public long BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public long Price { get; set; }
        public DateTime CreateTimeStamp { get; set; }
        public DateTime UpdateTimeStamp { get; set; }
        public bool IsDeleted { get; set; }
    }
}